# Generated by Django 2.1.9 on 2019-06-27 10:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_geosource", "0009_source_slug"),
        ("terra_layer", "0018_auto_20190626_0956"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublayers",
                        to="terra_layer.Layer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublayers",
                        to="django_geosource.Source",
                    ),
                ),
            ],
        )
    ]
