# Generated by Django 2.0.13 on 2019-07-02 12:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("terra_layer", "0022_auto_20190628_0928")]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="interactions",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
