# Generated by Django 2.2.7 on 2019-12-09 08:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terra_layer", "0044_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="tree",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
