# Generated by Django 2.2.7 on 2019-12-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terra_layer", "0045_scene_tree"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layer", options={"ordering": ("order", "name")},
        ),
        migrations.AlterModelOptions(
            name="layergroup", options={"ordering": ["order", "label"]},
        ),
        migrations.AlterField(
            model_name="layer",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="layers",
                to="terra_layer.LayerGroup",
            ),
        ),
    ]
