# Generated by Django 2.2.7 on 2019-12-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terra_layer", "0046_auto_20191210_1437"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="layergroup", unique_together=set(),),
    ]
