# Generated by Django 3.1.1 on 2020-09-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mapbox_baselayer", "0005_auto_20191202_1840"),
        ("terra_layer", "0049_auto_20200316_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="baselayer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mapbox_baselayer.mapbaselayer",
            ),
        ),
    ]
