dist: bionic
sudo: required
language: python
python:
- '3.6'
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=2.2 REST_VERSION=3.8
  - DJANGO_VERSION=2.2 REST_VERSION=3.9
  - DJANGO_VERSION=2.2 REST_VERSION=3.10
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10-postgis-2.4
    - postgresql-10-pgrouting
stages:
- lint
- test
- deploy
install:
- sudo apt-get -y install libproj-dev binutils gdal-bin
- pip install -e .[dev]
- pip install codecov
- if [[ $DJANGO_VERSION == dev ]]; then pip install -e git+https://github.com/django/django@master#egg=django;
  else pip install Django==$DJANGO_VERSION -U; fi
- if [[ $REST_VERSION == dev ]]; then pip install -e git+https://github.com/encode/django-rest-framework.git@master#egg=django-rest-framework;
  else pip install djangorestframework==$REST_VERSION -U; fi
before_script:
- psql -c "CREATE USER travis_ci_test WITH ENCRYPTED PASSWORD 'travis_ci_test';" -U
  postgres
- psql -c "ALTER USER travis_ci_test WITH SUPERUSER;" -U postgres
- psql -c 'CREATE DATABASE travis_ci_test WITH OWNER travis_ci_test;' -U postgres
- psql -d travis_ci_test -c 'CREATE EXTENSION postgis;'
- psql -d travis_ci_test -c 'CREATE EXTENSION pgrouting;'
after_failure:
- pip freeze
script:
- coverage run ./manage.py test
- codecov
jobs:
  include:
  - stage: lint
    install:
    - pip install flake8
    script:
    - flake8 terra_layer
  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      user: "__token__"
      password:
        secure: JBpgx4RJyjVOHZAmajqjuArEQltCt1SsDNTrthl2QGDhpqqX5Mj7qxUl1ffI49QwBgZArewzQhyqGthWT4UcBc+vtL6yA9qJpYAqVhtue1oVkf1cEOdZ6EqwD30EKmCjW6YVODQbMX80gNsxI3G5puc+6Pwjxwzuo4T8Qmu9GwTt6ZBUT/OGlZ1JwRSWNRAL/0Qvo7wAPoAZMRudwjeHQwIr/yrMv02s3UB5cAynfqq+Cg97iPlg+7w7kn6pc8cMTXmlAZ+QBHM68llzARxL4zSxQBx1DIF5oU77g02mcOpWzqlZlHt9moVeheIaUfZ9nSPhBcD44oYS8f0LC5qT2P+GUwQviiXl+iXZrEfxmfzNlb5QiOYkLUCVTsZ3Y6Ip4PyWR8Q6RTn+4jMeSUjZQic+S5BvoDU5Pc+OF2uyEwra2FfOmSpbhKiuQy3Y6tj4s9g9bWjik75FNLjimrJVNgfgsPbVPJW0V7S8W4f9a8nBpIfoXGNG3//23U2B2jygQYCFh5a5iGHZCV+DqD0KnxU76znvxw/XhOgjFAPh9rjK+kMINnkMcBukkrOL4/acPpe/089QoDhuS8UC+xcXs0OYx4M5MWIMTU2LGx2yiDvTS+vHBkvpiphyAmDqtuw3BPJaAg2xivOG1VVYcfBYPW6AcRuJfLZAC9C7VBPK60g=
      on:
        tags: true
