dist: bionic
sudo: required
language: python

python:
- '3.6'
- '3.7'
- '3.8'

env:
  matrix:
  - DJANGO_VERSION=2.2.*
  - DJANGO_VERSION=3.0.*
  - DJANGO_VERSION=dev

stages:
- lint
- test
- deploy

install:
- sudo apt-get -y install libproj-dev binutils gdal-bin
- pip install -e .[dev]
- pip install codecov
- if [[ $DJANGO_VERSION == dev ]]; then pip install -e git+https://github.com/django/django@master#egg=django;
  else pip install Django==$DJANGO_VERSION -U; fi

before_script:
- sudo docker-compose up -d postgres;
- sleep 5s;

after_failure:
- pip freeze

script:
- coverage run ./manage.py test
- codecov

jobs:
  allow_failures:
    - env: DJANGO_VERSION=dev

  include:
  - stage: lint
    install:
    - pip install black
    before_script: skip
    script:
    - black --check terra_layer
  #-
  #  install:
  #  - pip install flake8
  #  script:
  #    - flake8 terra_layer

  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      user: "__token__"
      password:
        secure: JBpgx4RJyjVOHZAmajqjuArEQltCt1SsDNTrthl2QGDhpqqX5Mj7qxUl1ffI49QwBgZArewzQhyqGthWT4UcBc+vtL6yA9qJpYAqVhtue1oVkf1cEOdZ6EqwD30EKmCjW6YVODQbMX80gNsxI3G5puc+6Pwjxwzuo4T8Qmu9GwTt6ZBUT/OGlZ1JwRSWNRAL/0Qvo7wAPoAZMRudwjeHQwIr/yrMv02s3UB5cAynfqq+Cg97iPlg+7w7kn6pc8cMTXmlAZ+QBHM68llzARxL4zSxQBx1DIF5oU77g02mcOpWzqlZlHt9moVeheIaUfZ9nSPhBcD44oYS8f0LC5qT2P+GUwQviiXl+iXZrEfxmfzNlb5QiOYkLUCVTsZ3Y6Ip4PyWR8Q6RTn+4jMeSUjZQic+S5BvoDU5Pc+OF2uyEwra2FfOmSpbhKiuQy3Y6tj4s9g9bWjik75FNLjimrJVNgfgsPbVPJW0V7S8W4f9a8nBpIfoXGNG3//23U2B2jygQYCFh5a5iGHZCV+DqD0KnxU76znvxw/XhOgjFAPh9rjK+kMINnkMcBukkrOL4/acPpe/089QoDhuS8UC+xcXs0OYx4M5MWIMTU2LGx2yiDvTS+vHBkvpiphyAmDqtuw3BPJaAg2xivOG1VVYcfBYPW6AcRuJfLZAC9C7VBPK60g=
      on:
        tags: true
